/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx al
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx au
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx bu
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx c
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx CF
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx cs
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx cu
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx FG
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx hc
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx i
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx j
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx jd
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx jm
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx l
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx m
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx MA
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx ni
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx Ol
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx p
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx pb
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx pp
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx rb
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx RM
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx ru
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx sn
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx SR
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx TA
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx v
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx WH
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx y
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx ZC
/Users/runzhou/sp/bin/python ~/fu_pred/fu_pred.py ~/fu_pred/rawdata.xlsx zn